### ISSUE TITLE
No measurements for stat node.clientstats.connected.smb in influxdb

### ISSUE THREAD

**Issue by eschek87** [Isilon/isilon_data_insights_connector#33]
In isi_data_insights_d.cfg  in section [cluster_client_activity_stats] i have added "node.clientstats.connected.smb", but i have no measurement in influxdb

**Comment by apecoraro** [comment]
Can you run it in debug mode for a minute or so and then post the output? To run in debug:
1. First stop the daemon if it is already running: ./isi_data_insights_d.py stop
2. Run with "debug": ./isi_data_insights_d.py debug
3. Use ctrl-C to stop it after a minute or so.

**Comment by eschek87** [comment]
Ok. I had run it in debug mode and attached the file. I have also tested the isiol stats browser and was able to see values.
[output.txt](https://github.com/Isilon/isilon_data_insights_connector/files/1127364/output.txt)

**Comment by apecoraro** [comment]
Your log indicates you are gathering node.clientstats.connected.cifs, which is a synonym for node.clientstats.connected.smb. Since you said you added node.clientstats.connected.smb, I'm thinking perhaps you added a new stat group section to the config file and then didn't add that new stat group to the active_stat_groups config file parameter. The active_stat_groups parameter is on or around line 28.

However, if you just wanted to add node.clientstats.connected.smb, you don't have to worry about it, since node.clientstats.connected.cifs gives you the same data. If you wanted to add other new stats in a new stat group then you have to remember to add the new stat group to the active_stat_groups parameter.

**Comment by eschek87** [comment]
Thanks for that information.
If i comment node.clientstats.active.cifs and add node.clientstats.active.smb1 in [cluster_client_activity_stats]
and restart the deamon i have no data in influxdb

**Comment by apecoraro** [comment]
Post your config file and your log file and I might be able to help you.

**Comment by eschek87** [comment]
[isi_data_insights_d.cfg.txt](https://github.com/Isilon/isilon_data_insights_connector/files/1137743/isi_data_insights_d.cfg.txt)
[isi_data_insights_d.log.txt](https://github.com/Isilon/isilon_data_insights_connector/files/1137744/isi_data_insights_d.log.txt)

**Comment by apecoraro** [comment]
Ok I see what is happening. I will work on a fix for you. A quick-work-around that you can use until I have the fix done is to change line 14 of isi_stats_client.py from this:
```
MAX_DIRECT_METADATA_STATS = 200
```
to this:
```
MAX_DIRECT_METADATA_STATS = 0
```
Give that a try and see if you see the node.clientstats.connected.smb going into InfluxDB (instead of as node.clientstats.connected.cifs).

**Comment by apecoraro** [comment]
Or actually just grab the latest code, I just merged a change that should fix your issue.

**Comment by eschek87** [comment]
Thanks!
