### ISSUE TITLE
grafana_cluster_protocol_dashboard.json 

### ISSUE THREAD

**Issue by eschek87** [Isilon/isilon_data_insights_connector#36]
Is it correct that the row "Average Latency by $protocol Operation for $cluster" has as "nullPointMode": "connected"? So that queries with a value of 0 are shown as connected and not as "null"? It seems that sometimes some metrics like "enumrate_snapshot" are not present and have therefore no values. And some classes are missing like "session_state", "create", "other" and "read" or "write". Is this intend?

**Comment by apecoraro** [comment]
I forwarded this question to the team that designed the dashboards. Their response was:

It is really a matter of personal preference on how you like seeing the data.

Personally I would prefer grafana to connect the dots where there is data and show gaps in the data as gaps i.e. Not connected.   However I could not get it to that when I created the dashboards.  That may have changed since then.

Could you post a screen shot of what you are describing to give me an idea what it looks like on a live cluster?

**Comment by eschek87** [comment]
![connected](https://user-images.githubusercontent.com/22763868/30060637-86bf4672-9244-11e7-88c6-05862d0cfcae.png)
Sorry for the delay. I have attached 2 screenshots. The "without_connected" is the grafana setting "Null value: null as zero" and the second "connected" has the setting "Null value: connected"
![without_connected](https://user-images.githubusercontent.com/22763868/30060632-827b3490-9244-11e7-989b-e569adc483ee.png)
