### ISSUE TITLE
Pruning data older than X days

### ISSUE THREAD

**Issue by mylesuyema** [Isilon/isilon_data_insights_connector#56]
Our influxdb VM has run out of space. Is there an easy way to prune older data to make room for new?

**Comment by fr3man1** [comment]
Hello,
Such issue can be fixed by aplying retention policy on your used databases.
Usually it is isi_data_insights, so instead of autogen policy, create something like three month, or whatever you feel required. 

Good read:
https://www.influxdata.com/blog/influxdb-shards-retention-policies/
Docs:
https://docs.influxdata.com/influxdb/v1.7/query_language/schema_exploration#show-retention-policies

**Comment by mylesuyema** [comment]
Awesome links. Thanks!
