### ISSUE TITLE
Bytes free and total per node

### ISSUE THREAD

**Issue by thestraycat** [Isilon/isilon_data_insights_connector#63]
Hi guys, would it be possible to add:

Bytes total per node
Bytes free per node
% used per node 

It would be super handy :)

**Comment by thestraycat** [comment]
subject changed

**Comment by tenortim** [comment]
Hi @thestraycat,
we can add graphs, but you also do this very easily yourself.
The per node space stats are:
```
node.ifs.bytes.free
node.ifs.bytes.used
node.ifs.bytes.total
```
Just add these to a stat group, and then graph them as you would like.
For the per-node percentage used, this is slightly trickier with Grafana because you're using two metrics/series, not one with multiple named values. So you need to follow the guidelines at [Grafana issue 1302](https://github.com/grafana/grafana/issues/1302).

**Comment by tenortim** [comment]
Closing based on my previous comment
