### ISSUE TITLE
Unable to install requirements.txt

### ISSUE THREAD

**Issue by tchuiselg** [Isilon/isilon_data_insights_connector#64]
Good morning:

I have the following error:

[root@ncias-d2060-v isilon_data_insights_connector]# pip install -r requirements.txt
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting daemons>=1.3.0 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/4c/06/839e9057afe8f6b0add5b93982ddd945dfb04706645edb89ceff0d7155b4/daemons-1.3.0.tar.gz
Collecting influxdb>=2.12.0 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/b7/eb/ff503c3195c2bfcf53be1deca10396e9e7b55096ccb51ee94aef54434f33/influxdb-5.2.2-py2.py3-none-any.whl
Requirement already satisfied: pip>=8.0.2 in /usr/lib/python2.7/site-packages/pip-19.0.1-py2.7.egg (from -r requirements.txt (line 3)) (19.0.1)
Collecting urllib3>=1.13.1 (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl
Collecting isi_sdk_8_0<0.2.0,>=0.1.2 (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/82/7d/32789058de4c872df5fd74c84971a3145662d254b919676fae8d98740a1b/isi_sdk_8_0-0.1.11-py2.py3-none-any.whl
Collecting isi_sdk_7_2<0.2.0,>=0.1.2 (from -r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/f4/47/c8013d306cf82e1a4feab3b2bf0e1792a53c96b6931fe5b6605bac15cda6/isi_sdk_7_2-0.1.11-py2.py3-none-any.whl
Collecting Equation>=1.2.01 (from -r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/fd/0d/ede829e7c0c457b651de2792cd19a739e4885477f59832da54d2cc7a1982/Equation-1.2.01.tar.gz
    Complete output from command python setup.py egg_info:

    The required version of setuptools (>=2.1) is not available,
    and can't be installed while this script is running. Please
    install a more recent version first, using
    'easy_install -U setuptools'.

    (Currently using setuptools 0.9.8 (/usr/lib/python2.7/site-packages))

    ----------------------------------------
**Command "python setup.py egg_info" failed with error code 2 in /tmp/pip-install-Tfy7Jh/Equation/**

I am a starter please don't be too hard on me

**Comment by tucked** [comment]
@tchuiselg It looks like your version of `setuptools` is ancient (0.9.8 is from July 2013) 😁 

There are a couple things going on here...
The essence of the issue is that you need to upgrade setuptools.
That can be done easily with this command:
``` sh
pip install --upgrade setuptools
```
- Note: `easy_install` is effectively deprecated and should not be used directly.

I would advise setting up a virtualenv first, though, because using `pip` to modify system packages _could_ break your system. (Remember, `apt`/`yum`/etc. is the system package manager, not `pip`, and some other package may depend on the version of `setuptools` you currently have installed.)
These commands should get you going:
``` sh
virtualenv my_venv  # If you don't have virtualenv,
                    # you can install it with your system package manager.
                    # e.g. `yum install python-virtualenv` or `apt-get install virtualenv`
source my_venv/bin/activate
pip install --upgrade pip setuptools wheel
pip install -r requirements.txt
```
More info on virtualenvs is available here:
https://packaging.python.org/guides/installing-using-pip-and-virtualenv/

**Comment by tchuiselg** [comment]
Thank you doing hat fixed indeed the issue installing requirement, but now I have this when I try to run the 
./isi_data_insights_d.py start
Invalid args provided to influxdb_plugin: ['localhost', '8086', 'isi_data_insights\nclusters
thank you again for your assistance

**Comment by tchuiselg** [comment]
[root@ncias-d2060-v isilon_data_insights_connector]# ./isi_data_insights_d.py start
Unable to load stats processor: influxdb_plugin
and then it displays my credentials can you help me with this please?

**Comment by tucked** [comment]
@tchuiselg Unfortunately, I am not very familiar with this project 😕 Apparently it may be in the process of being handed off to another team. I have pinged the manager of the new team, but he likely won't be able to respond until next week.

**Comment by tchuiselg** [comment]
Thank you I will wait till then thank you for you assistance.

**Comment by tucked** [comment]
@tchuiselg Just sanity-checking... Is the virtualenv still activated when you run that?
``` sh
source my_venv/bin/activate
./isi_data_insights_d.py start
```
or
```
my_venv/bin/python ./isi_data_insights_d.py start
```

**Comment by tchuiselg** [comment]
I did not activated my_venv is that a source of issue?

**Comment by tucked** [comment]
@tchuiselg Yes, that is likely the problem.
When you ran the steps from my first comment, dependencies from `requirements.txt` were installed into the virtual environment (i.e. `my_venv/lib/python2.7/site-packages`) instead of to the system (e.g. `/usr/lib/python2.7/site-packages`). So, in order to use those dependencies, you must either activate the virtual environment with `source my_venv/bin/activate` or use the `python` provided by the virtual environment (i.e. `my_venv/bin/python`).

**Comment by tenortim** [comment]
@tchuiselg were you able to start the collector?

**Comment by tchuiselg** [comment]
Hello I have not been able to make it work and stopped that project, if I resume I will let you know thanks for the follow up

Loic Gaetan Tchuise (Contractor)
Octo Consulting
Infrastructure and IT Operations Branch
National Cancer Institute
Center for Biomedical Informatics and Information Technology
9609 Medical Center Drive, 1W812
Rockville, MD 20850
Email: loic.tchuise@nih.gov<mailto:loic.tchuise@nih.gov>
Phone: 2402765901 (office)
[cid:image001.png@01D4D4F1.368AA610]

**Comment by tenortim** [comment]
Thank you for the response. I'm going to be working to update the project and apologize for the hiatus. If you are interested in using the collector in the future, please feel free to reach out to me.
